# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91971fe186b6b451702b269eeca13d65ad971c0283dd18ceaedfd6f45027d13aea429280abbcd88dec5840664029e618ed5ab8b6fd308b92f76b7e037f4d3649

test:
  secret_key_base: 4fad80520776a6c216a21a4328572bf93c2f5da518aa4cb008d88b43c4cf8c63889f3ca5da79f22f61b3a4056319ce73cebb67439285c4175b63379f738b355e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
